syntax = "proto3";
package ledger;

import "google/protobuf/timestamp.proto";

message Account {
  string account_id = 1;
  
  string user_id = 2;
  double balance = 3;
  string currency = 4;
}


message TransactionEntry {
  string id = 1;
  string account_id = 2;
  double amount = 3;
  string currency = 4;
  Type type = 5;
  google.protobuf.Timestamp created_at = 6;

  enum Type {
    DEBIT = 0;   // списание
    CREDIT = 1;  // зачисление
  }
}

message Balance {
  string account_id = 1;
  double available = 2;
  double pending = 3;
  string currency = 4;
}
